### ISSUE TITLE
<bonaparte-collapsible> not alway working

### ISSUE THREAD

**Issue by peranosborn** [bonaparte/bonaparte.io#18]
Sometimes the content is not hidden when the open attribute is set to false. This was noted in Chrome Version 50.0.2661.102 (64-bit). This looks like in is a webkit where the heigh is not set correctly if an element doesn't has a display property in the CSS. 

Fix :

``` CSS
bonaparte-collapsible[data-open="false"],
bonaparte-collapsible[open="false"] {
  display: inherit;
}
```
